### PR TITLE
snap: Add snapcraft.yaml file

### PR DESCRIPTION
**Pull request by guilhermepiccoli**
This commit introduces support for bundling/delivering gifski through
the 'snap' mechanism/store - more details at http://snapcraft.io.

"A snap is a bundle of your app and its dependencies that works without
modification across Linux. Snaps are discoverable and installable from
the Snap store, an app store with an audience of millions." [1]

In case the support/snapcraft.yaml file is accepted it can be published
in the Snap Store [2] which is required for people to easily install it.

Assistance for publishing in the snap store is available if required.

Test Procedure
==============

*Build/Snap
-----------

$ lxc launch ubuntu:16.04 snapcrafting  # create 'snapcrafting' container
$ lxc exec snapcrafting -- su - ubuntu  # execute user shell in container

$ sudo snap install snapcraft --classic # install snapcraft tool/commands

$ [get this snapcraft.yaml file]
$ snapcraft

...
 [Relatively large build output]
Snapped gifski_0.8.5_amd64.snap
...

*Install/Contents
-----------------

$ sudo snap install gifski_0.8.5_amd64.snap --dangerous # '--dangerous' is required as this isn't from the store.

$ which gifski
/snap/bin/gifski

*Testing
--------

$ wget -q http://techslides.com/demos/sample-videos/small.webm
$ ffmpeg -i small.webm frame%04d.png

$ gifski -o anim.gif frame*.png
$ ls -lh anim.gif
<...> 11M Dec  5 13:57 anim.gif

References:
[1] "Creating a snap" in https://docs.snapcraft.io/creating-a-snap
[2] "Share with your friends" in https://docs.snapcraft.io/rust-applications

Signed-off-by: Guilherme G. Piccoli <gpiccoli@canonical.com>
[This commit message was highly based in the great template from
Mauricio Faria de Oliveira at https://github.com/kornelski/pngquant/commit/a8e7d1e]

### CODE REVIEW

**Comment by kornelski** [comment]
Should it declare somewhere that `gcc` is required? OpenMP still doesn't work with clang AFAIK.

**Comment by guilhermepiccoli** [comment]
> Should it declare somewhere that `gcc` is required? OpenMP still doesn't work with clang AFAIK.

Thank you for the quick response! It's a good question - I wasn't sure, so asked the snapcraft maintainers, and the answer is that we don't need anything in the yaml, gcc is forcibly used in the rust plugin of snapcraft, here: https://github.com/snapcore/snapcraft/blob/master/snapcraft/plugins/rust.py#L85

Cheers!

**Comment by kornelski** [comment]
Great. Thanks!

**Comment by guilhermepiccoli** [comment]
Thank you, for accepting the PR =)

**Pull request merged**
