### PR TITLE
Revert to time-based frame collection

### PR DESCRIPTION
**Pull request by CL-Jeremy**
Sorry. I was too troubled by the warning **irrefutable while-let pattern** and messed up the logic.

If you may, you could squash it to make the history look tidier. I'm fine with either way.

### CODE REVIEW

**Comment by CL-Jeremy** [comment]
Sorry, there is still a problem with this. Please don't merge now.

**Comment by CL-Jeremy** [comment]
Revert back to time-based frame collection. Relying on perfectly rounded TS (to centiseconds) was a flaw.

Now the behavior matches FFmpeg again.

GitHub could add a function to turn an open PR back to draft (though I could simple change the title to **`[WIP] ...`**)

**Comment by kornelski** [comment]
Please rebase on master:

```sh
git rebase origin/master -Xours
```

**Comment by CL-Jeremy** [comment]
Like this?

**Comment by kornelski** [comment]
Almost. You've rebased on an older commit. `git fetch` and try again.

**Comment by CL-Jeremy** [comment]
Is it not allowed to do so? That's the history I'd like to wipe from the commit log (ed3b1f...978628).

**Comment by kornelski** [comment]
You can only edit history that isn't public. Once a commit has been accepted as a PR, it stays *forever*, and you can only build on top of that.

**Comment by kornelski** [comment]
Thanks for the fix

**Pull request merged**
