### PR TITLE
feat: add product tutorial

### LINKED ISSUE #309: Docs: Product Tutorial
## Problem 
Hi @kornelski! I’ve been using GIFSki for a while now, and I’m loving it! :) Anyway, I noticed that the repository does not have a tutorial for the product. 
## Possible Solution 
A brief tutorial on how to use this product would be helpful, especially users who are new to it. 
## Additional Information 
I’d love to create this document

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR provides a step-by-step tutorial on how to create a GIF using GIFSki. 
## Benefit
This will aid new users on how to effectively use this product. 

## Related Issues
Closes #309 

Note to Reviewers
This is the first time I created a product tutorial, so your feedback would be helpful @kornelski! :)

### CODE REVIEW

**Comment by NotOfficer** [comment]
I dont wanna sound rude but the app is very self explaining.
This seems kinda out of place to me but opinions are different.

**Comment by CBID2** [comment]
> I dont wanna sound rude but the app is very self explaining.
> 
> This seems kinda out of place to me but opinions are different.

Hi @NotOfficer. I struggled with using GIFSKI when I first used it, so I decided to add this page so other new users won't experience the same thing. Sometimes, the obvious things aren't so obvious.

**Comment by kornelski** [comment]
Thank you for your work on this. However, there's been a bit of a misunderstanding. This particular repository is for the underlying library and a command-line tool, not the macOS app in the video. The app has been developed [by somebody else](https://sindresorhus.com/gifski).

Also I did not expect the docs in the form of a video. Git repositories are technically a poor fit for storing large binary files like videos.

**Comment by CBID2** [comment]
> Thank you for your work on this. However, there's been a bit of a misunderstanding. This particular repository is for the underlying library and a command-line tool, not the macOS app in the video. The app has been developed [by somebody else](https://sindresorhus.com/gifski).
> 
> 
> 
> Also I did not expect the docs in the form of a video. Git repositories are technically a poor fit for storing large binary files like videos.
> 
> 
> 
> 

Hi @kornelski! 😄 Thanks for clarifying about the repository. I really thought this was where the app is hosted.

**Comment by kornelski** [comment]
There is an irony that GIFs aren't a good format, even for a GIF-making tool.

The repository for the Mac app is here: https://github.com/sindresorhus/Gifski

Note that its [website](https://sindresorhus.com/gifski) and [readme](https://github.com/sindresorhus/Gifski/blob/main/readme.md) already have images showing the steps. Sindre may like the particular design and wallpaper used in the images. I think the simplest and least controversial thing you can do is to add text description for each of the existing image steps in the readme, explaining what to do exactly.

**Comment by CBID2** [comment]
Thanks @kornelski! :)

**Pull request closed without merging**
